version: "3.7"
services:
  data-prepper:
    image: opensearch-data-prepper:1.2.0-SNAPSHOT
    container_name: data-prepper
    working_dir: /usr/share/data-prepper/
    command: sh data-prepper-wait-for-os-and-start.sh
    volumes:
      - ./data-prepper-wait-for-os-and-start.sh:/usr/share/data-prepper/data-prepper-wait-for-os-and-start.sh
      - ./pipelines.yaml:/usr/share/data-prepper/pipelines.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml
    ports:
      - "4900:4900" # DataPrepperServer port
      - "2021:2021" # OTelTraceSource port
    depends_on:
      - opensearch

  opensearch:
    container_name: node-0.example.com
    image: opensearchproject/opensearch:latest
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node

  opensearch-dashboard:
    container_name: opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_URL: https://node-0.example.com:9200
      OPENSEARCH_HOSTS: https://node-0.example.com:9200
